server:
  port: ${PORT:8090}

spring:
  datasource:
    url: jdbc:mysql://localhost:6543/interdel
    username: root
    password: admin
  flyway:
    url: jdbc:mysql://localhost:6543
    user: root
    password: admin
    schemas: interdel
    baseline-on-migrate: true

services:
  payment:
    url: ${SERVICE_PAYMENT_URL:http://localhost:8091/api/payment}